### ISSUE TITLE
Refactor block editor window resizing

### ISSUE THREAD

**Issue by MatzElectronics** [parallaxinc/BlocklyProp-cdn#156]
This will need to be done in conjunction with a refactor of the HTML layout of the editor's window in solo and BlocklyProp away from a table-based layout.  Example code is provided at the [Blockly Developer Site](https://developers.google.com/blockly/guides/configure/web/resizable)

**Comment by zfi** [comment]
Testing the code from PR #159 and finding that the vertical is way off on the latest versions of Firefox and Chrome. If I open and then close the Developer Tools in Chrome, the editor canvas refreshes to show the project and the left menu, but the canvas is truncated about 70px below the bottom of the left menu. This behavior is exhibited in both browsers. 

![2019-07-29_15-58-13](https://user-images.githubusercontent.com/8442260/62088365-f7090200-b219-11e9-972b-08cc00e43ada.png)

**Comment by zfi** [comment]
Update: The PR for Solo was not complete. After implementing that PR, the left menu and prject blocks appear as expected in the Chrome browser but not in the Firefox browser.

![2019-07-29_16-33-38](https://user-images.githubusercontent.com/8442260/62089755-0c345f80-b21f-11e9-9469-444303e76885.png)

**Comment by zfi** [comment]
Which PR addressed this issue? I am still seeing this with the latest commits from CDN and Solo.

**Comment by MatzElectronics** [comment]
[CDN-169](https://github.com/parallaxinc/BlocklyProp-cdn/commit/09ebf990ee2bd09f3834393098a1f4f0bdd4ac7a).  We might need to screenshare on this - I'm not able to replicate after this fix.
