### ISSUE TITLE
Save Project code is not detecting offline mode

### ISSUE THREAD

**Issue by zfi** [parallaxinc/BlocklyProp-cdn#165]
In reference to issue parallaxinc/solo#30,  When the user responds to the timer modal to save the project, the code in editor.js:saveProject() does not attempt to determine if the save operation is for online or offline persistence.  When the save operation fails in offline mode, the code assumes that there was an authentication failure.

**Comment by pjewald** [comment]
This issue is resolved. Closing the issue.
