### ISSUE TITLE
ReferenceError in latest.js

### ISSUE THREAD

**Issue by zfi** [parallaxinc/BlocklyProp-cdn#173]
When accessing the production BlocklyProp site, there is a ReferenceError triggered in the CDN/latest.js file at approximately line 64. This appears to be the code that is enumerating the latest projects - which is not functioning on Demo at this time. It's quite possible that the two observations are related.
```
latest.js:64 Uncaught ReferenceError: getURLParameter is not defined
    at Object.<anonymous> (latest.js:64)
    at Function.each (jquery-1.11.3.min.js:2)
    at Object.success (latest.js:63)
    at j (jquery-1.11.3.min.js:2)
    at Object.fireWith [as resolveWith] (jquery-1.11.3.min.js:2)
    at x (jquery-1.11.3.min.js:5)
    at XMLHttpRequest.b (jquery-1.11.3.min.js:5)
```

```
$.get("rest/shared/project/list?sort=modified&order=desc&limit=5&offset=0", function (data) {
    // Loop through each row returned
    $.each(data['rows'], function (index, project) {
-->>       if (getURLParameter('debug')) console.log(project);

        var user = '';

        // Set the user name for use in the anchor element below
```

**Comment by MatzElectronics** [comment]
The fix is pretty straightforward: either delete the line causing the error
(it's just for debugging), or include utils.js (or the getURLParameter
function from that file inline).

**Comment by zfi** [comment]
I'll get this one.

**Comment by zfi** [comment]
Verified that the code block works without the code that was removed. 
Closing this issue.
