### ISSUE TITLE
Bulk Projects (downloaded) won't open in Solo v1.3.497

### ISSUE THREAD

**Issue by PropGit** [parallaxinc/BlocklyProp-cdn#226]
As of v1.3.497, suddenly some projects that were bulk downloaded won't open.

Editor appears briefly then disappears; back to home page.

![Bulk Project Open Fail](https://user-images.githubusercontent.com/1266318/67506295-a69b1800-f641-11e9-9fe2-8b3b67e53abf.gif)

**Comment by zfi** [comment]
Can you attach one or more of the project files that are causing this issue? Also, please test this against Solo version 1.3.497 which was released this morning (10/24/2019). That version has code specific to .svge project imports.

**Comment by PropGit** [comment]
:-)  I am testing against 1.3.497.

I've determined that the project files from yesterday and today are the same (except for one I modified, but that's not the one I'm testing).

The attached zip contains all of them.  badge_wx_giveaway(2075).svge is the first one I noticed wouldn't render.  It's a large project.  Worked fine yesterday.  The badge_wx..._3 and 4, etc. are also large and affected by this behavior.

[BlocklyPropProjects.zip](https://github.com/parallaxinc/BlocklyProp-cdn/files/3768620/BlocklyPropProjects.zip)

**Comment by zfi** [comment]
The projects that trigger this behavior appear to be PROPC board type. We disabled all of the PROPC board type code in Solo, so this is actually working correctly. It **would** be nice if the app let the user know that this is unsupported. Or, we could enable the PROPC board type, warts and all.

**Comment by PropGit** [comment]
Okay, somethings wrong with that... the PROPC board type projects actually open.  The Badge WX board type projects are the ones that are failing.  The names are confusing because I was experimenting with this project.  Here's the details:

![image](https://user-images.githubusercontent.com/1266318/67508524-05629080-f646-11e9-9015-291af6e1fc7e.png)

**Comment by PropGit** [comment]
The files in the archive seem to correspond to this list, in order, even though the names don't match completely.

Question: was the board type disabling done yesterday afternoon/evening?  This all worked when I tested yesterday, but not today.

**Comment by PropGit** [comment]
When testing this time, I opened the console.  It very briefly (about 0.25 sec) displays an error then clears.  Had to take a video capture and look frame-by-frame to read it.

It says:

[Intervention] Blocked attempt to show a 'beforeunload' confirmation panel for a editor.js:447 frame that never had a user gesture since its load.  https://www.chromestqatus.com/feature/5082396709879808

**Comment by MatzElectronics** [comment]
I see the bug:
![image](https://user-images.githubusercontent.com/19737272/67509628-45c30e00-f648-11e9-929b-0c0eedcd396a.png)

@PropGit what you found is an effect of this one.

@zfi is the Blockly core in solo newer than demo or production?  Part of the reason for my haste with this last round of PRs is to address issues like this that I saw coming after the dev conference.  The error is coming from the comment block when it tries to render it.  It ends up in a sort of loop, and blockly fails it because it's exceeding its stack size.  Since the error happens in the try catch, the catch here is kicking the user back to the home page.

The PR related to hidden fields in solo should address this.

**Comment by MatzElectronics** [comment]
The board type isn't the issue, it's what blocks are in your project...

**Comment by PropGit** [comment]
@MatzElectronics - Thanks.  What I don't understand is why did this all work yesterday and not today.  That Try/Catch haven't changed since then, right?  I can guarantee the projects have not changed.

**Comment by MatzElectronics** [comment]
I don't understand that either...

**Comment by zfi** [comment]
The project is failing here.

```
function loadToolbox(xmlText) {
    if (Blockly.mainWorkspace) {
        let xmlDom = Blockly.Xml.textToDom(xmlText);
-->>>    Blockly.Xml.domToWorkspace(xmlDom, Blockly.mainWorkspace); 
    }
}

DOMException: Failed to execute 'querySelectorAll' on 'Element': '*,:x' is not a valid selector.
    at http://localhost:8082/src/lib/jquery-1.11.3.min.js:24:10706
    at ja (http://localhost:8082/src/lib/jquery-1.11.3.min.js:24:7594)
    at ga.setDocument (http://localhost:8082/src/lib/jquery-1.11.3.min.js:24:10444)
    at http://localhost:8082/src/lib/jquery-1.11.3.min.js:24:22040
    at http://localhost:8082/src/lib/jquery-1.11.3.min.js:24:22760
    at http://localhost:8082/src/lib/jquery-1.11.3.min.js:24:207
    at http://localhost:8082/src/lib/jquery-1.11.3.min.js:24:212

```

**Comment by MatzElectronics** [comment]
@PropGit - can you diff the project downloaded today versus one downloaded earlier?  I wonder if its in the XML of the svge file, if that's changed somehow.

**Comment by zfi** [comment]
What is different is that Solo now has abut 6 weeks of updates. I'll check to see what core is in place.

**Comment by zfi** [comment]
We're still using a version 2 blockly core.

**Comment by PropGit** [comment]
> @PropGit - can you diff the project downloaded today versus one downloaded earlier? I wonder if its in the XML of the svge file, if that's changed somehow.

I did already, they are exactly the same, and I tried opening the same project from the archive of yesterday and it fails now too.

**Comment by PropGit** [comment]
Based on Matt's "comment block" note: I opened one of the offending projects in Demo and removed nearly all code that is not comments to simplify it down to this (below) then Download Projects... BAM... still fails to open in Solo.

![image](https://user-images.githubusercontent.com/1266318/67510812-7f951400-f64a-11e9-9e41-3958b650b437.png)
[badge_wx_giveaway_mybe(2328).zip](https://github.com/parallaxinc/BlocklyProp-cdn/files/3768758/badge_wx_giveaway_mybe.2328.zip)

**Comment by PropGit** [comment]
Maybe this has something to do with it?  Every time I try to do a Save As in Demo, it keeps selecting Hackable Electronic Badge as the project type... but my type is Badge WX.

**Comment by PropGit** [comment]
When selecting Badge WX before saving, it warns me that I'm changing the project type to a possible incompatible type.  This is crazy.. the project STARTED as a Badge WX, never a Hackable Electronic Badge.  I'm thinking the broken feature is in Demo, and Solo is just suffering the consequences.

**Comment by PropGit** [comment]
Here's a totally different Badge WX project.  I opened, then Saved As.  See the Icon in the upper-right?  That's a Badge WX icon (the Hackable badge icon is tall and thin).

![image](https://user-images.githubusercontent.com/1266318/67511305-72c4f000-f64b-11e9-8050-b56565c37cc7.png)

**Comment by zfi** [comment]
Many of the projects I have in Demo are simple. They all seem to load into the current version of Solo without error. I am working though the projects you provided earlier, and I'll add the latest one to test.

As for the board type oddness on Demo, I will have to stick a pin in that and resolve it later.

**Comment by PropGit** [comment]
I just found that if I take out the separator comment blocks to make it look more like this, then it opens in Solo.

![image](https://user-images.githubusercontent.com/1266318/67511922-ae13ee80-f64c-11e9-8cc0-fff9f9037094.png)

**Comment by zfi** [comment]
This seems to validate what @MatzElectronics was saying earlier. I'll take a look at the PR he mentions and see if that can apply to the v2.x of the blockly core.

**Comment by PropGit** [comment]
Okay.  Now I've verified that if I simply go back to the original project, remove the separator comment blocks and Save As (Badge WX, of course), then it opens in Solo fine (like yesterday, but now without 4 blocks).

[badge_wx_giveaway_gd(2334).zip](https://github.com/parallaxinc/BlocklyProp-cdn/files/3768840/badge_wx_giveaway_gd.2334.zip)

**Comment by MatzElectronics** [comment]
If you want to just do the smalled possible change, look at the changes to base.js in solo-127

**Comment by zfi** [comment]
The PR that @MatzElectronics referenced in Solo is parallaxinc/solo#127. There is a lot to unpack there. I will see if I can cherry-pick changes to the specific block and apply them. We just don't have the time to test 10 blocks.

**Comment by PropGit** [comment]
Does this explain why it worked yesterday and not today?  I'm still mystified about that.

**Comment by MatzElectronics** [comment]
Me too.

**Comment by zfi** [comment]
I responded to this earlier in the thread and in email. An update to Solo was published this morning to correct the.svge.issue. The previous update was published about 6 weeks ago. The blockly core was updated from version 1 to version 2-July-2019. We still have not implemented core 3.x.

**Comment by zfi** [comment]
@MatzElectronics, I cherry picked the updates to the base.js file but I am still seeing the stack overrun error when I try to change a comment block to a comment spacer block. 

```
blockly_compressed.js:1664 Uncaught RangeError: Maximum call stack size exceeded
    at Blockly.FieldDropdown.render_ (blockly_compressed.js:1664)
    at Blockly.FieldDropdown.Blockly.Field.getSize (blockly_compressed.js:1434)
    at Blockly.BlockSvg.renderCompute_ (blockly_compressed.js:1571)
    at Blockly.BlockSvg.render (blockly_compressed.js:1566)
    at Blockly.Input.insertFieldAt (blockly_compressed.js:1443)
    at Blockly.Input.appendField (blockly_compressed.js:1442)
    at Blockly.BlockSvg.updateShape_ (base.js:1278)
    at Blockly.FieldDropdown.validator_ (base.js:1279)
    at Blockly.FieldDropdown.Blockly.Field.setValue (blockly_compressed.js:1438)
    at Blockly.BlockSvg.Blockly.Block.setFieldValue (blockly_compressed.js:1477)
```

**Comment by MatzElectronics** [comment]
Okay - I ran into that when I was working on these, that's why it looked familiar.  It's basically stuck in a loop - the updateShape_ function gets called when the block is being built, so it then re-builds it, and that change triggers updateShape() again, and on and on it goes.  I can't get back to it for a few hours, but I'll try to see if I can solve it as soon as I'm able.

**Comment by pjewald** [comment]
Projects exported from the Demo system and subsequently imported into Solo were failing because, in part, because the comment blocks configured to provide white space in the block diagram were failing to render correctly. This has been addresses in parallaxinc/solo#132.

With the new code in place, I am now able to load the projects originally reported as failing to load.

**Comment by zfi** [comment]
This issue has been resolved by correcting the error in the Comment block that was embedded in the projects that failed.

Closing this issue.
