### ISSUE TITLE
Missing configure_term_config() function

### ISSUE THREAD

**Issue by zfi** [parallaxinc/BlocklyProp-cdn#227]
The onClick handler for the terminal graph setup button in editor.js is set to call configure_term_graph(), but the function is nowhere to be found in the project. The missing call was introduced in PR #129 and appears to have been broken since then. Is there code for this somewhere?

```
$('#term-graph-setup').on('click', () => configure_term_graph());
```

**Comment by pjewald** [comment]
This issue also exists in the Solo project. We need to correct it in both projects.

**Comment by zfi** [comment]
bump.. Any progress on this issue?

**Comment by MatzElectronics** [comment]
This is a call to a not-yet-written function that was designed to allow someone who is using the experimental code-only mode to set up graphing and terminal baud rate.  It can be safely commented out or removed, along with the HTML element that contains it (which should already have a "propc-only" or "code-only" class).

**Comment by MatzElectronics** [comment]
I'll wait for direction on whether we should delete the associated HTML element, or simply comment out the javascript.

**Comment by zfi** [comment]
Closing this issue.
