### ISSUE TITLE
Firefox reporting error when loading a private project

### ISSUE THREAD

**Issue by zfi** [parallaxinc/BlocklyProp-cdn#77]
Firefox version 63 is reporting
``` 
SecurityError: The operation is insecure.
```
when opening a private project. Specifically, it is complaining about the console.log line. Can the call be replaced or removed? 
```
    // Copy the client download and run instructions 
    // from the client instruction page to the modal that also shows them
    $("#client-instructions-copy").html($("#client-instructions-original").html());
    
    console.log(navigator.browserSpecs);
});
```

**Comment by MatzElectronics** [comment]
Unless it's causing the editor to choke - I'd opt to leave this in for the time being.  It's there to help Jeff diagnose any weirdness with customers when they are having issues with chromebooks or client software - he can direct the customer to retrieve this, and then provide guidance accordingly.

Something to look at in the future is to send this info the the client, where it can then report it.

**Comment by zfi** [comment]
Ideally, that data should appear either in a popup dialog window or perhaps logged. Sending it to the console triggers the error when the user is on the HTTPS version of the web site.

Let's leave this issue open until the matter is resolved.
