### ISSUE TITLE
Source map error 403

### ISSUE THREAD

**Issue by zfi** [parallaxinc/BlocklyProp-cdn#78]
Developer console is logging a source map error when loading a private project. 

Using FireFox version 63 - MacOS 10.14.1

```
Source map error: request failed with status 403 
Resource URL: https://s3.amazonaws.com/aws-blockly-cdn.parallax.com/prod/8/lib/chartist.min.js
Source Map URL: chartist.min.js.map
```

The file is available at the same URL as the Resource URL noted in the error. Attempts to load the file from the resource URL are successful.

**Comment by MatzElectronics** [comment]
I need some guidance on how to fix this...

**Comment by zfi** [comment]
It appears that this is a bootstrap package issue and was corrected in bootstrap 3.3.7 last year.

https://github.com/MaxCDN/bootstrapcdn/issues/629

**Comment by MatzElectronics** [comment]
Ugh...we are on Bootstrap 2.x... going to 3+ is a MAJOR change.

**Comment by pjewald** [comment]
This should be corrected as part of the pending issue to upgrade the underlying bootstrap package.

**Comment by MatzElectronics** [comment]
I figured out what these are.  At the end of the .min files in many of our dependencies, there are commented out links...apparently the browser is trying to talk to them.  They can be safely deleted.
I'll delete them as I update dependencies as part of that process.

**Comment by MatzElectronics** [comment]
https://developer.mozilla.org/en-US/docs/Tools/Debugger/How_to/Use_a_source_map

We don't need this feature.

**Comment by zfi** [comment]
The issue is resolved. Closing.
