### ISSUE TITLE
New Color Picker select does not release select highlighting

### ISSUE THREAD

**Issue by zfi** [parallaxinc/BlocklyProp-cdn#85]
The color picker block has an issue where, after selecting a color from the palate, the color picker color component appears to remain selected as if the item was selected for a copy and paste operation. Selecting any other control (such as the block/code toggle) shows that control in the same mode (copy and paste operation). The current code base on Demo highlights this issue.

**Comment by MatzElectronics** [comment]
I think I need this to shown to me - selecting a new value within a block does not release selection for any block who's menu or dropdown has been changed - you have to click away from the block to de-select it.  Can you confirm please?

**Comment by zfi** [comment]
Steps to reproduce the issue (on the Demo server):

* Drop a color block onto the pallet
![screen shot 2019-02-19 at 19 13 03](https://user-images.githubusercontent.com/8442260/53063948-decad500-347a-11e9-94cd-5d9646b98e44.png)

* Click on the white area of the block to open the color palate
![screen shot 2019-02-19 at 19 13 42](https://user-images.githubusercontent.com/8442260/53063991-028e1b00-347b-11e9-86b0-2c41c5aa10ea.png)

* Select a color to dismiss the color palate.  Move the mouse to the Code/Block selector. 

![screen shot 2019-02-19 at 19 14 31](https://user-images.githubusercontent.com/8442260/53064016-1a659f00-347b-11e9-9c66-c3ea3426e881.png)

* The word 'Code' is highlighted. Clicking on the Code/Block button switched to the code window, where all of the code is highlighted as if the text were selected.

![screen shot 2019-02-19 at 19 14 54](https://user-images.githubusercontent.com/8442260/53064110-716b7400-347b-11e9-8bb5-ec168de7f1f7.png)

I tried to click away from the block by clicking on an open area of the editor screen but it seemed to have no effect on this issue. I should note that this example was done on the latest version of Firefox. I'll try it again with Chrome in a few minutes.

**Comment by MatzElectronics** [comment]
Okay - I was able to replicate in Firefox on Mac.  Not entirely sure how to track this one down, but just clicking somewhere away form the highlight seems to clear it.  It's as if a mousedown is being held (maybe by a stray .preventDefault() somewhere?)
