### ISSUE TITLE
Unable to open WebSocket if client browser is using https in Firefox

### ISSUE THREAD

**Issue by zfi** [parallaxinc/BlocklyProp-cdn#92]
Observation:
When a Firefox browser is connected to the BlocklyProp web site using a secure (HTTPS) connection, and the user attempts to open a project (demo or personal), the editor page appears but the UI elements for the project, the left menu and many of the buttons in the nav bar are not rendered. 

Details:
Firefox is throwing a SecurityError in blocklypropclient.js, line 241 that appears to be ignored while attempting to open a WebSocket. The call returns up the stack and ends up in an endless loop within jQuery where it is detecting a DOMException, throws an error, detects the error, and continues ad-nausea. 

It is noted that current versions of Chrome (68-70) do not appear to be affected by this issue. 

```
try {
    var connection = new WebSocket(url);
    } catch(e) {
        if(e.name !== "SecurityError") {
            throw e;
        } else {
            // Do something sane here;
        }
    }
```

**Comment by zfi** [comment]
There is a workaround in Firefox to disable the SecurityError detection when accessing a WebSocket. 

WARNING: This workaround is not recommended and is provided here as a diagnostic tool.
```
Access the about:config settings page in Firefox and and toggle the network.websocket.allowInsecureFromHTTPS  setting to true.
```

**Comment by PropGit** [comment]
Thank you @zfi.  This certainly will help me test the solution(s) I'll work on.
