### ISSUE TITLE
Compress js and css files to improve load times

### ISSUE THREAD

**Issue by zfi** [parallaxinc/BlocklyProp-cdn#95]
The JavaScript files for the project are currently published in an uncompressed format. The supporting libraries are already minified by their respective publishers. This task will convert the remaining JavaScript and CSS files to their minified counterparts to reduce the file size and improve cleitn load times.

**Comment by pjewald** [comment]
We rolled this back in favor of a larger, long term strategy that will be implemented after a refactor to ES6.
